// Incident tests for the setup console. One per bug that actually happened, or
// per credential whose failure is silent. Nothing here tests a function name.
import { test, describe, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { spawn, execFile } from 'node:child_process'
import { readFile, unlink } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { isLoggedIn, sigv4Headers } from '../scripts/console/checks.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const sh = (cmd, args, opts = {}) => new Promise((res) =>
  execFile(cmd, args, { cwd: ROOT, ...opts }, (e, o, s) => res({ code: e?.code ?? 0, out: `${o}${s}` })))

describe('incident: wrangler whoami exits 0 while saying you are not logged in', () => {
  // The wizard ran `whoami >/dev/null || login`, so login never fired and setup
  // died nine lines later asking for an API token it had never mentioned.
  test('an exit code cannot answer the question, the words can', () => {
    assert.equal(isLoggedIn('You are not authenticated. Please run `wrangler login`.'), false)
    assert.equal(isLoggedIn(''), false)
    assert.equal(isLoggedIn(undefined), false)
    assert.equal(isLoggedIn('👋 You are logged in with an OAuth Token, associated with the email a@b.com.'), true)
    assert.equal(isLoggedIn('│ Account Name │ Account ID │'), true)
  })
})

describe('the QR code on the setup page', () => {
  // A QR that does not scan is worse than no QR: it looks finished. Generated by
  // CoreImage and read back by CoreImage's own detector, which is what a phone
  // camera is doing.
  test('scans back to the otpauth URI it was drawn from', { skip: process.platform !== 'darwin' }, async () => {
    const uri = 'otpauth://totp/Survival?secret=JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP&issuer=Survival&digits=6&period=30'
    const png = join(tmpdir(), `qr-test-${process.pid}.png`)
    const gen = await sh('/usr/bin/osascript', ['-l', 'JavaScript', 'scripts/qr.js', uri, png, '8'])
    assert.equal(gen.code, 0, gen.out)
    const decoder = join(tmpdir(), `qrdec-${process.pid}.js`)
    await (await import('node:fs/promises')).writeFile(decoder, `
      ObjC.import('CoreImage'); ObjC.import('Foundation')
      function run(argv) {
        const img = $.CIImage.imageWithContentsOfURL($.NSURL.fileURLWithPath($.NSString.alloc.initWithUTF8String(argv[0])))
        const fs = $.CIDetector.detectorOfTypeContextOptions('CIDetectorTypeQRCode', $(), $()).featuresInImage(img)
        return fs.count === 0 ? 'NONE' : ObjC.unwrap(fs.objectAtIndex(0).messageString)
      }`)
    const read = await sh('/usr/bin/osascript', ['-l', 'JavaScript', decoder, png])
    await Promise.all([unlink(png).catch(() => {}), unlink(decoder).catch(() => {})])
    assert.equal(read.out.trim(), uri)
  })
})

describe('the R2 key check', () => {
  // R2 keys are used by a sidecar on a box nobody is watching. A wrong pair means
  // backups that never happened, discovered at restore time. Signed against a
  // real S3 server so the signer is proved, not asserted.
  const HOST = '127.0.0.1:9000'
  const labUp = () => fetch(`http://${HOST}/minio/health/live`, { signal: AbortSignal.timeout(1500) })
    .then((r) => r.ok).catch(() => false)
  const ask = (secretKey) => fetch(`http://${HOST}/`, {
    headers: sigv4Headers({ method: 'GET', host: HOST, path: '/', accessKey: 'admin', secretKey }),
  })

  test('a correct key pair is accepted by a real S3 server', async (t) => {
    if (!(await labUp())) return t.skip('lab MinIO is not running')
    assert.equal((await ask('password123')).status, 200)
  })

  test('a wrong secret is rejected, not quietly accepted', async (t) => {
    if (!(await labUp())) return t.skip('lab MinIO is not running')
    assert.equal((await ask('wrong')).status, 403)
  })
})

describe('the setup console, running', () => {
  let port, token, proc

  before(async () => {
    port = 8800 + (process.pid % 100)
    proc = spawn('node', ['scripts/console/server.mjs'], {
      cwd: ROOT, env: { ...process.env, SETUP_PORT: String(port), SETUP_NO_OPEN: '1' },
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    // 15s was not enough on a loaded machine: this hook failed once during a
    // full-suite run and passed on its own seconds later. A test that fails
    // when the box is busy teaches you to re-run it until it agrees, which is
    // the one habit the gates in this repo exist to prevent. So it waits
    // longer, and when it does give up it says what the process actually said
    // instead of only that nothing arrived.
    let said = ''
    proc.stderr.on('data', (b) => { said += String(b) })
    token = await new Promise((resolve, reject) => {
      const t = setTimeout(
        () => reject(new Error(`the console never printed a link in 45s${said ? `. It said: ${said.trim()}` : ', and said nothing on stderr'}`)),
        45000,
      )
      proc.stdout.on('data', (b) => {
        const m = String(b).match(/\?t=([0-9a-f]+)/)
        if (m) { clearTimeout(t); resolve(m[1]) }
      })
    })
  })

  after(() => proc?.kill())

  const call = (path, body) => fetch(`http://127.0.0.1:${port}${path}`, {
    method: body === undefined ? 'GET' : 'POST',
    headers: { 'content-type': 'application/json', 'x-setup-token': token },
    body: body === undefined ? undefined : JSON.stringify(body),
  })

  test('a page on another site cannot drive it', async () => {
    const r = await fetch(`http://127.0.0.1:${port}/api/apply?t=${token}`, {
      method: 'POST', headers: { origin: 'https://evil.example' },
    })
    assert.equal(r.status, 403)
  })

  test('without the token there is nothing to see', async () => {
    assert.equal((await fetch(`http://127.0.0.1:${port}/`)).status, 403)
    assert.equal((await fetch(`http://127.0.0.1:${port}/api/state`)).status, 403)
  })

  test('no value ever comes back out of it', async () => {
    // The generated TOTP secret is in the process. The page is told it is verified
    // or not, never what it is. /api/totp/manual is the one deliberate exception.
    const body = await (await call(`/api/state?t=${token}`)).text()
    assert.equal(/[A-Z2-7]{32}/.test(body), false, `a base32 secret leaked into the state: ${body}`)
  })

  test('a filled-in field that failed its check does not count as done', async () => {
    // Present is not working. Requiring only that a value exists is how a token
    // that Cloudflare rejected reaches the deploy.
    await call(`/api/set?t=${token}`, { field: 'CF_API_TOKEN', value: 'not-a-real-token' })
    const stream = await call(`/api/apply?t=${token}`, {})
    const first = (await stream.text()).split('\n')[0]
    assert.match(first, /not ready yet/)
    assert.match(first, /Cloudflare API token/)
  })

  test('a wrong TOTP code is refused and a right one is not', async () => {
    const bad = await (await call(`/api/totp/verify?t=${token}`, { code: '000000' })).json()
    assert.equal(bad.ok, false)
    const { secret } = await (await call(`/api/totp/manual?t=${token}`)).json()
    const { totp } = await import('../src/totp.js')
    const good = await (await call(`/api/totp/verify?t=${token}`, { code: await totp(secret) })).json()
    assert.equal(good.ok, true)
  })
})
